[package]
name = "iot-app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "vanling"
path = "src/main.rs"

[features]
default = ["esp32c6-devkitc-1"]
esp32c6 = [
  "iot-chip-esp/esp32c6", "dep:esp-hal", "dep:esp-rtos",
  "esp-backtrace/esp32c6", "esp-bootloader-esp-idf/esp32c6",
  "esp-hal/esp32c6", "esp-println/esp32c6", "esp-rtos/esp32c6",
]
esp32c6-devkitc-1 = ["esp32c6", "iot-bsp-esp/esp32c6-devkitc-1"]
esp32s3 = [
  "iot-chip-esp/esp32s3", "dep:esp-hal", "dep:esp-rtos",
  "esp-backtrace/esp32s3", "esp-bootloader-esp-idf/esp32s3",
  "esp-hal/esp32s3", "esp-println/esp32s3", "esp-rtos/esp32s3",
]
lckfb-szpi-esp32s3 = ["esp32s3", "iot-bsp-esp/lckfb-szpi-esp32s3"]

[dependencies]
embassy-executor = { workspace = true }
embassy-futures = { workspace = true }
embassy-sync = { workspace = true }
embassy-time = { workspace = true }
embedded-alloc = { workspace = true }
esp-backtrace = { workspace = true, optional = true }
esp-bootloader-esp-idf = { workspace = true, optional = true }
esp-hal = { workspace = true, optional = true }
esp-println = { workspace = true, optional = true }
esp-rtos = { workspace = true, optional = true }
iot-bsp-esp = { workspace = true }
iot-chip-esp = { workspace = true }
iot-core = { workspace = true }
log = { workspace = true }